### ISSUE TITLE
WeChat detects user-agent and refuses to load in the sidebar

### ISSUE THREAD

**Issue by dbw9580** [slobber/wechat-sidebar#3]
See screenshot:
![screenshot_20181112_213419](https://user-images.githubusercontent.com/6999708/48351044-f815f580-e6c3-11e8-9e12-9c5b05e2fb91.png)

On Firefox 63.0.1, Debian Buster.

**Comment by dbw9580** [comment]
Okay, I figured this out.
This was caused by the co-existence of the testpilot add-on "Side View", which adds a request listener to inject mobile device user-agent into request headers:
https://github.com/mozilla/side-view/blob/9a41f9644a2405588ba9fc49c1926d4c1f3cf7ba/addon/background.js#L291

Wechat-sidebar is afftected because the RequestFilter used by Side View does not differentiate different instances of sidebar views (the one opened by Side View and the one by Wechat-sidebar), because the api only permits the use of `tabs.TAB_ID_NONE` to filter out all non-browser tabs:
https://github.com/mozilla/side-view/blob/9a41f9644a2405588ba9fc49c1926d4c1f3cf7ba/addon/background.js#L223
As a result, requests made by Wechat-sidebar are intercepted and modified by Side View.

Work around this issue by either
1. disabling "Side View", or
2. opening "https://wx.qq.com/" from "Side View" and clicking "Ask for Desktop Site" button on the popup, then opening wechat-siderbar again.

**Comment by slobber** [comment]
Thanks for your issue. I reviewed the side-view code, and found the second one, add domain to 'desktopHostnames' should be the general solution. 

https://github.com/mozilla/side-view/blob/9a41f9644a2405588ba9fc49c1926d4c1f3cf7ba/addon/background.js#L371

I'll close this issue, thanks again.
